import { z } from 'zod'

/**
 * §10 question bank.
 *
 * The three §10.1 types are genuinely different shapes, not one shape with
 * optional fields: an MCQ without options is meaningless, a video question
 * without a rubric cannot be graded. A discriminated union rejects those at the
 * edge rather than letting a half-formed question reach an exam.
 */

/**
 * §6.2: English is required; Hindi and Gujarati are optional at creation.
 *
 * Written out rather than generated by a helper with computed keys
 * (`[`${field}En`]`): TypeScript widens those to `string`, so the field names
 * stop existing at the type level and Prisma can no longer verify that
 * questionTextEn — a NOT NULL column — is actually being written.
 */
const requiredEn = (label: string) => z.string().trim().min(1, `English ${label} is required`)
const optionalText = z.string().trim().optional()

/**
 * §10.3 metadata every question must carry.
 *
 * NOTE — topicId is required here but nullable in §4.1's schema. §10.3 says
 * "Every question must have ... Topic", so the API enforces it while the column
 * stays permissive for imported legacy rows. Same for the source reference.
 */
const baseQuestion = z.object({
  difficulty: z.enum(['easy', 'medium', 'hard']).default('medium'),
  topicId: z.string().uuid('A topic is required (§10.3)'),
  departmentId: z.string().uuid('A department is required'),
  /** NULL means the question applies to every outlet (§4.1). */
  outletId: z.string().uuid().nullable().optional(),

  designationLevelMin: z.coerce.number().int().min(1).max(5).optional(),
  designationLevelMax: z.coerce.number().int().min(1).max(5).optional(),

  questionTextEn: requiredEn('question text'),
  questionTextHi: optionalText,
  questionTextGu: optionalText,

  explanationEn: optionalText,
  explanationHi: optionalText,
  explanationGu: optionalText,

  instructionsEn: optionalText,
  instructionsHi: optionalText,
  instructionsGu: optionalText,

  imageUrl: z.string().url().optional(),
  videoUrl: z.string().url().optional(),
  audioUrl: z.string().url().optional(),

  marks: z.coerce.number().positive('Marks must be greater than zero').max(999).default(1),
  timeLimitSeconds: z.coerce.number().int().positive().max(3600).optional(),

  sourceDocumentId: z.string().uuid().optional(),
  sourceChapter: z.string().trim().max(255).optional(),
  sourcePage: z.string().trim().max(50).optional(),
  tags: z.array(z.string().trim().min(1).max(50)).max(20).optional(),
})

/** §10.1 type 1 — MCQ: 4 options, exactly one correct. */
const mcqOption = z.object({
  id: z.string().trim().min(1).max(50),
  textEn: requiredEn('option text'),
  textHi: optionalText,
  textGu: optionalText,
  isCorrect: z.boolean(),
  imageUrl: z.string().url().optional(),
})

/**
 * §10.1's option rules, defined ONCE.
 *
 * The update schema previously re-declared this as a bare `.array(mcqOption)
 * .length(4)` and silently lost both refinements — so a PATCH could store an
 * MCQ with zero or two correct answers. With zero, correctOptionId() returns
 * null at grading time, every candidate is marked wrong, and negative marking
 * penalises them for a question that had no right answer.
 */
const mcqOptions = z
  .array(mcqOption)
  // §10.1: "4 options (A, B, C, D)".
  .length(4, 'An MCQ must have exactly 4 options')
  .refine((opts) => opts.filter((o) => o.isCorrect).length === 1, {
    message: 'An MCQ must have exactly one correct option',
  })
  .refine((opts) => new Set(opts.map((o) => o.id)).size === opts.length, {
    message: 'Option ids must be unique',
  })

const mcqQuestion = baseQuestion.extend({
  type: z.literal('mcq'),
  options: mcqOptions,
  /** §10.1 supports negative marking, configurable per question. */
  negativeMarks: z.coerce.number().min(0).max(999).optional(),
})

/** §10.1 type 2 — Theory: open response, model answer for the grader. */
const theoryQuestion = baseQuestion.extend({
  type: z.literal('theory'),
  // The model answer the grader is shown (§10.1).
  expectedAnswerEn: optionalText,
  expectedAnswerHi: optionalText,
  expectedAnswerGu: optionalText,
  minWordLimit: z.coerce.number().int().positive().max(5000).optional(),
  maxWordLimit: z.coerce.number().int().positive().max(5000).optional(),
})

/** §10.1 type 3 — Video/Image: staff upload a response, graded against a rubric. */
const rubricCriterion = z.object({
  criterion: z.string().trim().min(1, 'Criterion is required').max(255),
  maxMarks: z.coerce.number().positive('Criterion marks must be greater than zero'),
  description: z.string().trim().max(1000).optional(),
})

const videoImageQuestion = baseQuestion.extend({
  type: z.literal('video_image'),
  responseType: z.enum(['image', 'video', 'both']),
  // §10.1: 50MB video, 10MB image, 2 minutes.
  maxFileSizeMb: z.coerce.number().int().positive().max(50).optional(),
  maxVideoDurationSeconds: z.coerce.number().int().positive().max(600).optional(),
  rubric: z
    .array(rubricCriterion)
    .min(1, 'A video/image question needs at least one rubric criterion')
    .max(10),
})

export const createQuestionSchema = z
  .discriminatedUnion('type', [mcqQuestion, theoryQuestion, videoImageQuestion])
  .superRefine((q, ctx) => {
    if (
      q.designationLevelMin !== undefined &&
      q.designationLevelMax !== undefined &&
      q.designationLevelMin > q.designationLevelMax
    ) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['designationLevelMin'],
        message: 'Minimum designation level cannot exceed the maximum',
      })
    }

    if (q.type === 'theory' && q.minWordLimit !== undefined && q.maxWordLimit !== undefined) {
      if (q.minWordLimit > q.maxWordLimit) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['minWordLimit'],
          message: 'Minimum word limit cannot exceed the maximum',
        })
      }
    }

    if (q.type === 'video_image') {
      // The rubric IS the mark scheme. If its criteria do not sum to the
      // question's marks, a grader awarding full marks on every criterion
      // produces a score that does not match what the exam expects.
      const total = q.rubric.reduce((sum, c) => sum + c.maxMarks, 0)
      if (Math.abs(total - q.marks) > 0.001) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['rubric'],
          message: `Rubric criteria total ${total} but the question is worth ${q.marks} marks`,
        })
      }
    }

    // §10.3 requires a source reference. A document id or a free-text chapter
    // both satisfy it — not every SOP is uploaded yet.
    if (!q.sourceDocumentId && !q.sourceChapter) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['sourceDocumentId'],
        message: 'A source reference is required (§10.3): a document, or a chapter reference',
      })
    }
  })

/**
 * Updates cannot change `type`: the type decides which columns are meaningful,
 * so switching an approved MCQ to theory would leave its options orphaned and
 * its model answer empty. Delete and recreate instead.
 */
export const updateQuestionSchema = z
  .object({
    difficulty: z.enum(['easy', 'medium', 'hard']).optional(),
    topicId: z.string().uuid().optional(),
    departmentId: z.string().uuid().optional(),
    outletId: z.string().uuid().nullable().optional(),
    designationLevelMin: z.coerce.number().int().min(1).max(5).optional(),
    designationLevelMax: z.coerce.number().int().min(1).max(5).optional(),
    questionTextEn: z.string().trim().min(1).optional(),
    questionTextHi: z.string().trim().optional(),
    questionTextGu: z.string().trim().optional(),
    explanationEn: z.string().trim().optional(),
    explanationHi: z.string().trim().optional(),
    explanationGu: z.string().trim().optional(),
    instructionsEn: z.string().trim().optional(),
    instructionsHi: z.string().trim().optional(),
    instructionsGu: z.string().trim().optional(),
    imageUrl: z.string().url().nullable().optional(),
    videoUrl: z.string().url().nullable().optional(),
    audioUrl: z.string().url().nullable().optional(),
    marks: z.coerce.number().positive().max(999).optional(),
    negativeMarks: z.coerce.number().min(0).max(999).optional(),
    timeLimitSeconds: z.coerce.number().int().positive().max(3600).nullable().optional(),
    options: mcqOptions.optional(),
    expectedAnswerEn: z.string().trim().optional(),
    expectedAnswerHi: z.string().trim().optional(),
    expectedAnswerGu: z.string().trim().optional(),
    minWordLimit: z.coerce.number().int().positive().max(5000).nullable().optional(),
    maxWordLimit: z.coerce.number().int().positive().max(5000).nullable().optional(),
    responseType: z.enum(['image', 'video', 'both']).optional(),
    maxFileSizeMb: z.coerce.number().int().positive().max(50).optional(),
    maxVideoDurationSeconds: z.coerce.number().int().positive().max(600).optional(),
    rubric: z.array(rubricCriterion).min(1).max(10).optional(),
    sourceDocumentId: z.string().uuid().nullable().optional(),
    sourceChapter: z.string().trim().max(255).nullable().optional(),
    sourcePage: z.string().trim().max(50).nullable().optional(),
    tags: z.array(z.string().trim().min(1).max(50)).max(20).optional(),
  })
  .refine((v) => Object.keys(v).length > 0, { message: 'No fields to update' })

export const listQuestionsQuerySchema = z.object({
  type: z.enum(['mcq', 'theory', 'video_image']).optional(),
  difficulty: z.enum(['easy', 'medium', 'hard']).optional(),
  topic_id: z.string().uuid().optional(),
  department_id: z.string().uuid().optional(),
  outlet_id: z.string().uuid().optional(),
  status: z.enum(['draft', 'pending_review', 'approved', 'archived']).optional(),
  search: z.string().trim().max(200).optional(),
  /** §10.5: "Questions without Hindi/Gujarati translations". */
  missing_translation: z.enum(['hi', 'gu']).optional(),
  lang: z.enum(['en', 'hi', 'gu']).optional(),
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().max(100).default(20),
})

/** §10.2's review step. */
export const submitForReviewSchema = z.object({}).optional()

export const reviewSchema = z.object({
  comments: z.string().trim().max(2000).optional(),
})

export const rejectSchema = z.object({
  // A rejection with no reason is not actionable — the author cannot fix it.
  comments: z.string().trim().min(1, 'A reason is required when rejecting a question').max(2000),
})

export const idParamSchema = z.object({ id: z.string().uuid('Must be a valid question id') })

export type CreateQuestionInput = z.infer<typeof createQuestionSchema>
export type UpdateQuestionInput = z.infer<typeof updateQuestionSchema>
export type ListQuestionsQuery = z.infer<typeof listQuestionsQuerySchema>
export type ReviewInput = z.infer<typeof reviewSchema>
export type RejectInput = z.infer<typeof rejectSchema>
